# action.yaml
name: 'Terraform Cloud Trigger'
description: 'Call the terraform cloud api to start plans and applies'
inputs:
  workspace:
    description: 'name of your workspace'
    required: true
  org:
    description: 'name of your organization'
    required: true
  TFE_TOKEN:
    description: 'a terraform cloud token for api authorization'
    required: true
  type:
    description: 'determines whether to automatically apply the plan, defaults to false'
    required: false
    default: false
  target:
    description: 'targeting a specific resource'
    required: false
    default: ''
  message:
    description: 'message included with run'
    required: false
    default: 'Terraform Plan via terraform-cloud-trigger'
runs:
  using: 'docker'
  image: 'Dockerfile'