name: run terraform-cloud
on:
  push:
    branches:
      - dev

jobs:
  trigger-tf-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger TF Cloud Runs
        id: tag
        uses: hklauke/terraform-cloud-trigger:main
        with:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          type: plan
          workspace: fm-terraform-infra-dev
          org: flymachine

